# Generated by Django 4.1 on 2022-09-06 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='i̇l',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='i̇lçe',
            options={'verbose_name': 'District', 'verbose_name_plural': 'Districts'},
        ),
        migrations.AlterModelTable(
            name='i̇l',
            table='Cities',
        ),
        migrations.AlterModelTable(
            name='i̇lçe',
            table='Districts',
        ),
    ]
