# Generated by Django 4.1 on 2022-09-06 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseUser', '0002_remove_baseuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseuser',
            options={'verbose_name': 'BaseUser', 'verbose_name_plural': 'BaseUsers'},
        ),
        migrations.AlterModelTable(
            name='baseuser',
            table='BaseUsers',
        ),
    ]
