<<<<<<< HEAD
# Generated by Django 4.1 on 2022-09-20 17:31
=======
# Generated by Django 4.1 on 2022-09-20 19:52
>>>>>>> 00586e609e34c33e74f07fb0a99ad004ffe29811

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseUser', '0003_alter_baseuser_options_alter_baseuser_table'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='baseuser',
            managers=[
            ],
        ),
    ]
