# Generated by Django 4.1 on 2022-09-20 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseUser', '0003_alter_baseuser_options_alter_baseuser_table'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='baseuser',
            managers=[
            ],
        ),
    ]
