# Generated by Django 4.1.4 on 2022-12-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseUser', '0005_baseuser_is_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
