# Generated by Django 4.1.4 on 2023-02-01 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseUser', '0006_baseuser_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='password',
        ),
    ]
