# Generated by Django 4.1.4 on 2023-02-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseUser', '0007_remove_baseuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='password',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
