# Generated by Django 4.1.4 on 2023-02-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseUser', '0009_alter_baseuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
