# Generated by Django 4.1.4 on 2023-02-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseUser', '0013_alter_baseuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='is_employee',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='is_expert',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='is_regular',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'CUSTOMER'), (2, 'Expert'), (3, 'Employee')], null=True),
        ),
    ]
