# Generated by Django 4.1.4 on 2023-02-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseUser', '0014_remove_baseuser_is_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'CUSTOMER'), (1, 'Expert'), (3, 'Employee')], null=True),
        ),
    ]
