# Generated by Django 4.1.4 on 2023-02-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_employee_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.TextField(verbose_name='Şifre'),
        ),
    ]
