# Generated by Django 4.1 on 2022-09-23 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_alter_servicecategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='parent',
        ),
    ]
