# Generated by Django 4.1.4 on 2022-12-23 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0004_remove_servicecategory_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_category', to='Category.servicecategory'),
        ),
    ]
