# Generated by Django 4.1.4 on 2022-12-23 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0005_servicecategory_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='parent',
        ),
    ]
