# Generated by Django 4.1 on 2022-09-04 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BaseUser', '0001_initial'),
        ('ExpertUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalAccount',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('favoriteexperts', models.ManyToManyField(to='ExpertUser.expert')),
            ],
            options={
                'verbose_name': 'Kişisel Kullanıcı',
                'verbose_name_plural': 'Kişisel Kullanıcılar',
            },
        ),
    ]
