# Generated by Django 4.1 on 2022-09-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalaccount',
            name='current_lat',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='personalaccount',
            name='current_long',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=9),
        ),
    ]
