# Generated by Django 4.1 on 2022-09-06 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalUser', '0002_personalaccount_current_lat_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='personalaccount',
            table='PersonalUsers',
        ),
    ]
