# Generated by Django 4.1 on 2022-09-07 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalUser', '0003_alter_personalaccount_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalaccount',
            name='current_lat',
        ),
        migrations.RemoveField(
            model_name='personalaccount',
            name='current_long',
        ),
    ]
