# Generated by Django 4.1 on 2022-09-21 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalUser', '0005_alter_personalaccount_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalaccount',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
    ]
