# Generated by Django 4.1 on 2022-09-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpertUser', '0010_alter_openinghours_unique_together'),
        ('PersonalUser', '0006_alter_personalaccount_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalaccount',
            name='previusexpertcalls',
            field=models.ManyToManyField(related_name='previusexperts', to='ExpertUser.expert', verbose_name='Önceki Çağrılar'),
        ),
        migrations.AlterField(
            model_name='personalaccount',
            name='favoriteexperts',
            field=models.ManyToManyField(related_name='favoriteexperts', to='ExpertUser.expert', verbose_name='Favori Çağrılar'),
        ),
    ]
