# Generated by Django 4.1.4 on 2023-02-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalUser', '0010_alter_personalaccount_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalaccount',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='personalaccount',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
