# Generated by Django 4.1 on 2022-09-04 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BaseUser', '0001_initial'),
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('averagescore', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Ortalama Puan')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Category.servicecategory', verbose_name='Katagorisi')),
            ],
            options={
                'verbose_name': 'Uzman',
                'verbose_name_plural': 'Uzmanlar',
            },
        ),
    ]
