# Generated by Django 4.1 on 2022-09-06 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExpertUser', '0002_expert_lat_expert_long'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expert',
            options={'verbose_name': 'Expert', 'verbose_name_plural': 'Experts'},
        ),
        migrations.AlterModelTable(
            name='expert',
            table='Experts',
        ),
    ]
