# Generated by Django 4.1 on 2022-09-07 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_alter_servicecategory_options_and_more'),
        ('ExpertUser', '0003_alter_expert_options_alter_expert_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='averagescore',
        ),
        migrations.AddField(
            model_name='expert',
            name='closingtime',
            field=models.TimeField(null=True, verbose_name='Kapanış Zamanı'),
        ),
        migrations.AddField(
            model_name='expert',
            name='companyname',
            field=models.CharField(max_length=50, null=True, verbose_name='İşyeri İsmi'),
        ),
        migrations.AddField(
            model_name='expert',
            name='description',
            field=models.TextField(null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='expert',
            name='openingtime',
            field=models.TimeField(null=True, verbose_name='Açılış Zamanı'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Category.servicecategory', verbose_name='Kategorisi'),
        ),
    ]
