# Generated by Django 4.1 on 2022-09-20 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExpertUser', '0004_remove_expert_averagescore_expert_closingtime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'Pazartesi'), (2, 'Salı'), (3, 'Çarşamba'), (4, 'Perşembe'), (5, 'Cuma'), (6, 'Cumartesi'), (7, 'Pazar')], verbose_name='Weekday')),
                ('from_hour', models.TimeField(verbose_name='Opening')),
                ('to_hour', models.TimeField(verbose_name='Closing')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpertUser.expert', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Working time',
                'verbose_name_plural': 'Working times',
                'ordering': ['weekday', 'from_hour'],
            },
        ),
    ]
