# Generated by Django 4.1 on 2022-09-20 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExpertUser', '0005_openinghours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='closingtime',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='openingtime',
        ),
    ]
