# Generated by Django 4.1 on 2022-09-21 07:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ExpertUser', '0007_openinghours_is_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images', verbose_name='Expert Image')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpertUser.expert', verbose_name='Expert')),
            ],
            options={
                'verbose_name': 'Expert Image',
                'verbose_name_plural': 'Expert Images',
            },
        ),
    ]
