# Generated by Django 4.1 on 2022-09-22 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExpertUser', '0009_alter_expertimage_image_alter_openinghours_from_hour_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='openinghours',
            unique_together={('company', 'weekday')},
        ),
    ]
