# Generated by Django 4.1 on 2022-10-10 17:35

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0004_remove_servicecategory_level_and_more'),
        ('ExpertUser', '0011_remove_expert_category_expert_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertimage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='expertimage',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='expertimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='expertimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='expert',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='Category.servicecategory', verbose_name='Kategorisi'),
        ),
        migrations.AddIndex(
            model_name='expert',
            index=django.contrib.postgres.indexes.GinIndex(fields=['companyname'], name='bas_expert_ln_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
