# Generated by Django 4.1.4 on 2022-12-23 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0005_servicecategory_parent'),
        ('ExpertUser', '0012_alter_expert_categories_expert_bas_expert_ln_gin_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='categories',
        ),
        migrations.AddField(
            model_name='expert',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Category.servicecategory', verbose_name='Kategorisi'),
        ),
    ]
