# Generated by Django 4.1.4 on 2023-02-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpertUser', '0014_alter_expert_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='password',
            field=models.TextField(default='pbkdf2_sha256$390000$aFPItBeusjwW6y5YrbOSwY$bpQAkv4VVQBG5W+bc3pK2ybUHvmBBXvso7odOh5p4Sg=', verbose_name='Şifre'),
        ),
    ]
