# Generated by Django 4.1.4 on 2023-02-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpertUser', '0015_expert_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='password',
            field=models.TextField(verbose_name='Şifre'),
        ),
    ]
