# Generated by Django 4.1.4 on 2023-02-16 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0005_servicecategory_parent'),
        ('ExpertUser', '0016_alter_expert_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experts', to='Category.servicecategory', verbose_name='Kategorisi'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='companyname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='İşyeri İsmi'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=1.0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='expert',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=6, default=1.0, max_digits=9, null=True),
        ),
    ]
