# Generated by Django 4.1.4 on 2023-02-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpertUser', '0017_alter_expert_category_alter_expert_companyname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='expert',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
