# Generated by Django 4.1 on 2022-09-05 07:55

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalUser', '0002_personalaccount_current_lat_and_more'),
        ('ExpertUser', '0002_expert_lat_expert_long'),
        ('Comment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='expertreview',
            name='rating_once',
        ),
        migrations.AddField(
            model_name='expertreview',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AddField(
            model_name='expertreview',
            name='text',
            field=models.CharField(default='SomeText', max_length=200, verbose_name='Yorum Yazısı'),
        ),
        migrations.AlterField(
            model_name='expertreview',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpertUser.expert', verbose_name='Yorumu Yapılan Usta'),
        ),
        migrations.AlterField(
            model_name='expertreview',
            name='rate',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='puanlama'),
        ),
        migrations.AlterField(
            model_name='expertreview',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PersonalUser.personalaccount', verbose_name='Yorumu Atan Müşteri'),
        ),
    ]
