# Generated by Django 4.1 on 2022-09-06 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0002_remove_expertreview_rating_once_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expertreview',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelTable(
            name='expertreview',
            table='Reviews',
        ),
    ]
