# Generated by Django 4.1 on 2022-09-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0004_alter_expertreview_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertreview',
            name='isAnonymous',
            field=models.BooleanField(default=False),
        ),
    ]
