# Generated by Django 4.1.4 on 2022-12-15 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ExpertUser', '0012_alter_expert_categories_expert_bas_expert_ln_gin_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavExpert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ExpertUser.expert')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
