# Generated by Django 4.1.4 on 2022-12-20 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Favourite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfavexpert',
            options={'verbose_name_plural': 'User favourite experts'},
        ),
    ]
