# Generated by Django 4.1.4 on 2023-03-14 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExpertUser', '0018_alter_expert_lat_alter_expert_long'),
        ('GuestUser', '0001_initial'),
        ('Favourite', '0003_alter_userfavexpert_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestUserFavExpert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ExpertUser.expert')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='GuestUser.guestuser')),
            ],
            options={
                'verbose_name_plural': 'User favourite experts',
            },
        ),
    ]
